[FEATURE] Storage user with Redux
alkemyTech/OT102-Client pull request #13
Opened 2021-12-08 15:48 UTC by gabodmc

[OT102-43](https://alkemy-labs.atlassian.net/browse/OT102-43)
**AS:** Developer
**I WANT:** Manage the state with Redux
**To:** Unify the information flux 

**Accepted criteria:** 
A redux store is already configurated in the proyect. Add the reducer and the actions to login, logout and persist the user in state.

### Evidence
**User login simulation**
![1](https://user-images.githubusercontent.com/79473217/145238693-41f4c6de-dd19-4932-8cfa-3b15eb2a6809.png)
**User State setted**
![2](https://user-images.githubusercontent.com/79473217/145238696-32ac85ba-ae7c-468b-b368-1bbe60120a70.png)

2021-12-08 16:11 UTC, JonatanGarbuyo commented on src/app/slices/auth.js
> + * Function to get the user logged data in the state
agregale que es una función para pasarle al useSelect()

2021-12-08 16:12 UTC, JonatanGarbuyo approved these changes
re bien.
++ por los comentarios   :)

2021-12-08 21:56 UTC, maxicuyo94 approved these changes

2021-12-08 22:06 UTC, gabodmc commented on src/app/slices/auth.js
> + * Function to get the user logged data in the state
dale, le meto esta actualizada antes de mergear

2021-12-08 22:52 UTC, gabyMangoni approved these changes
ok

2021-12-08 22:52 UTC, joselo85 approved these changes

2021-12-08 22:54 UTC, dvelezroman requested changes

2021-12-08 22:54 UTC, dvelezroman commented on src/app/slices/auth.js
> +      state.userData = {}
mejor usar null

2021-12-08 22:54 UTC, dvelezroman commented on src/app/slices/auth.js
> +    userData: {},
mejor usar null

2021-12-08 22:54 UTC, dvelezroman commented on src/app/slices/auth.js
> +  dispatch(setUserData(response.data.body))
el token no guardarlo en el reducer.. el token va al local storage... hay que sacarlo del pbjeto antes de colocarlo en user

2021-12-08 23:09 UTC, gabodmc commented on src/app/slices/auth.js
> +    userData: {},
Si le pongo null, lintea como que no le estoy pasando un atributo sin nada.

2021-12-08 23:09 UTC, gabodmc commented on src/app/slices/auth.js
> +  dispatch(setUserData(response.data.body))
Si le pongo null, lintea como que no le estoy pasando un atributo sin nada.

2021-12-08 23:10 UTC, gabodmc commented on src/app/slices/auth.js
> +      state.userData = {}
Si le pongo null, lintea como que no le estoy pasando un atributo sin nada.

2021-12-08 23:10 UTC, gabodmc commented on src/app/slices/auth.js
> + * Function to get the user logged data in the state
agregado!

2021-12-09 14:06 UTC, alexiscjscab approved these changes

2021-12-09 14:16 UTC, dvelezroman approved these changes
bien ahi

2021-12-09 14:31 UTC, merged