[ WIP] [ PAGES ]  LIST CONTACTS -OT102 76
alkemyTech/OT102-Client pull request #15
Opened 2021-12-08 20:14 UTC by alexiscjscab

**DESCRIPTION :** 
AS admin user
I WANT to get the list of Contacts
TO keep track of the Contacts received. 

**Criteria of acceptance:**
- When entering the path / backoffice / contacts, show a list of Contacts sent on the site, obtained from the endpoint.
- This listing will be displayed in a table 

**Observation:** Missing add to route /back office  

**Evidence**
![7a28d8e3-8517-4315-aab4-c0877960a350](https://user-images.githubusercontent.com/74843944/145276860-60cda0d8-c2b3-486f-b244-e98135a82240.gif)

Mobile
![mobileContacts](https://user-images.githubusercontent.com/74843944/145277004-f4020b91-e423-47d1-bf3e-8ea144e77f42.png)

2021-12-08 22:55 UTC, dvelezroman commented
Se ve bien.. solo un comentario... la fuente mantener una sola para todo el proyecto..

2021-12-09 20:26 UTC, dvelezroman commented on src/pages/backoffice/listContacts.js
> +          <Tfoot bg="brand.cyan">
Revisar si este bloque va o no... porque se repite lo del header

2021-12-10 13:26 UTC, gabodmc commented
En lugar de un reducer, no seria mejor setearlo en un estado y mapearlo?

2021-12-10 17:10 UTC, dvelezroman approved these changes

2021-12-10 21:11 UTC, dvelezroman requested changes

2021-12-10 21:11 UTC, dvelezroman commented on src/app/slices/contacts.js
> +export const getContacts = () => async (dispatch) => {
mover esto a la logica del componente Contacts ....

2021-12-10 21:11 UTC, dvelezroman commented on src/pages/backoffice/listContacts.js
> +import { getContacts } from '../../app/slices/contacts'
manejar contact como stado del componente

2021-12-10 21:11 UTC, dvelezroman commented on src/pages/backoffice/listContacts.js
> +import { getContacts } from '../../app/slices/contacts'
`[contacts, setContact] = useState([])`

2021-12-10 23:58 UTC, closed without merging