[LAYOUT] Footer - OT102-22
alkemyTech/OT102-Client pull request #17
Opened 2021-12-09 01:24 UTC by Gabriiel99

Description
HOW: User
I WANT: View the footer of the page
TO: Have extra information about it

Acceptance criteria: Must show name, logo and link to social networks of the Organization. This data will be obtained from the public data endpoint.

3 columns

1.Logo of the ONG With name

2.Web links

3.Social media links
![Captura](https://user-images.githubusercontent.com/57367881/145317152-85e51e00-78a3-4809-aea8-db4fb3ec7b2e.PNG)

2021-12-09 13:52 UTC, JonatanGarbuyo approved these changes
parece que todo esta ok.  pero fallaron los checks..

2021-12-09 14:18 UTC, dvelezroman approved these changes
se ve bien.. solo arreglar ese conflicto que hay cunado buildea.

2021-12-09 20:16 UTC, dvelezroman commented on src/App.js
> +import Footer from './components/header/Footer'
cambiar ruta

2021-12-09 20:16 UTC, dvelezroman commented on src/App.js
> +// eslint-disable-next-line import/extensions
quitar este eslint error

2021-12-09 20:17 UTC, dvelezroman requested changes
pequenios cmabios

2021-12-10 17:09 UTC, dvelezroman approved these changes

2021-12-10 21:14 UTC, gabyMangoni approved these changes

2021-12-10 21:23 UTC, merged