[CONNECT] List and detail with API - OT102-58
alkemyTech/OT102-Client pull request #26
Opened 2021-12-13 03:57 UTC by gabyMangoni

OT102-58 - https://alkemy-labs.atlassian.net/browse/OT102-58
---------------------------------------------------------------------------------------------------------------------------------
**Description**
HOW: Developer
I WANT: Link the list of News with API
TO: Show content dynamically

**Acceptance criteria:** 
Link listing and detail screens with backend

--------------------------------------------------------------------------------------------------------------------------------
List News
![detalle-novedad-3](https://user-images.githubusercontent.com/79479608/145750018-18aa5104-15c4-48be-947d-ec52692ac82e.jpg)

Detail News Ok
![detalle-novedad](https://user-images.githubusercontent.com/79479608/145750035-9c14fe6e-7cde-429d-920c-c07b491afbc9.jpg)

Detail News Error
![detalle-novedad-2](https://user-images.githubusercontent.com/79479608/145750096-0b3ead65-9e16-4ba7-9632-f716e5f53ead.jpg)

2021-12-13 12:25 UTC, JonatanGarbuyo commented on src/pages/NewsDetail.js
> +        <Spinner />
el spinner deberia manejarse con un estado.
para mostrarlo y ocultarlo segun corresponda.

cuando estas solicitando la info le cambias el estado parra que sea visible
al recibir la info lo volves a ocultar.

2021-12-13 12:26 UTC, JonatanGarbuyo commented on src/pages/NewsDetail.js
> +        { error ? getErrorView() : getNews() }
el error lo ibamos a manejar con el Alert que hizo joselo

2021-12-13 12:27 UTC, JonatanGarbuyo requested changes
Hola Gabi. te deje algunos comentarios

2021-12-13 12:48 UTC, gabyMangoni commented on src/pages/NewsDetail.js
> +        { error ? getErrorView() : getNews() }
Esto ya me lo habian aprobado el viernes en News, solo replique lo mismo para NewsDetail. Pense o entendi que para la parte del cliente es mas visual un error asi que que te salte una alert. Tambien pense que lo del Alert era para los form de parte del admin. Como quieran. si se unifica lo cambio a los alert?

2021-12-13 12:51 UTC, gabyMangoni commented on src/pages/NewsDetail.js
> +        <Spinner />
Si.. en el mapeado de las news lo maneje asi.. pero aca lo habia usado mas por una cuestion estetica.. porque solo te lo muestra si trae error.. pero entiendo lo que decis.. puedo sacarlo de aca y manejarlo solo para el estado.. y/o dejarlo en los dos lados...  en estado y en el error. Como prefieran.

2021-12-13 15:00 UTC, dvelezroman approved these changes

2021-12-14 20:49 UTC, joselo85 approved these changes

2021-12-14 20:50 UTC, gabodmc approved these changes

2021-12-14 21:26 UTC, JonatanGarbuyo approved these changes

2021-12-15 00:50 UTC, merged