[] Connects register form with backend - OT102-65
alkemyTech/OT102-Client pull request #32
Opened 2021-12-15 01:37 UTC by JonatanGarbuyo

[OT102-65](https://alkemy-labs.atlassian.net/browse/OT102-65)

## Description
AS: User
I WANT: enter the site already logged in, automatically
TO: navigate the site quickly

## Acceptance criteria:
When the user registers on the site, he should automatically log in and
redirect to base path (/). To do this you need to modify the server
to return the token once the user is created and store the same
on the client side

## Evidence 

#### validation error
![validations](https://user-images.githubusercontent.com/58077441/146106744-979eba16-bf90-47e5-ac39-7f3acbb9bf61.png)

2021-12-15 15:16 UTC, gabodmc requested changes
Yo lo veo re bien... solo un comentario

2021-12-15 15:16 UTC, gabodmc commented on src/pages/auth/Register.js
> +    .min(6, 'Contraseña debe tener al menos 6 caracteres')
Fijate que el pass desde el back viene con 8 caracteres minimos. Y tmb habria que agregarle que necesita una mayuscula, minuscula, numero y caracter especial.

2021-12-15 17:04 UTC, JonatanGarbuyo commented on src/pages/auth/Register.js
> +    .min(6, 'Contraseña debe tener al menos 6 caracteres')
si. yo le agregue el de mayuscula, minuscula, numero y caracter especial  que no lo tenia.
ahi le cambio el 6

2021-12-15 17:15 UTC, gabodmc approved these changes

2021-12-16 13:18 UTC, dvelezroman approved these changes
excelente

2021-12-16 15:34 UTC, gabyMangoni approved these changes

2021-12-16 19:03 UTC, merged