[wip][SCREEN] UserProfile and edit OT102-26
alkemyTech/OT102-Client pull request #35
Opened 2021-12-15 15:27 UTC by maxicuyo94

Descripción
COMO: Usuario
QUIERO: Ver mi perfil
PARA: Modificar mis datos personales cuando lo requiera

Criterios de aceptación: El usuario podrá visualizar su nombre, apellido, email y dispondrá de las acciones de Editar Datos y Eliminar cuenta

https://alkemy-labs.atlassian.net/browse/OT102-26

2021-12-17 20:56 UTC, dvelezroman requested changes

2021-12-17 20:56 UTC, dvelezroman commented on src/pages/UserProfile.js
> +            navigate('/')
hacer Logout antes de redirigir a Home

2021-12-20 03:45 UTC, gabodmc approved these changes

2021-12-20 12:17 UTC, gabyMangoni approved these changes

2021-12-20 20:40 UTC, dvelezroman approved these changes

2021-12-22 21:13 UTC, merged